name: SquadBeyond RPA

on:
  repository_dispatch:
    types: [run-rpa]

jobs:
  run-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm init -y
          # ★修正: Stealthプラグインを追加インストールする
          npm install playwright axios playwright-extra puppeteer-extra-plugin-stealth
          npx playwright install --with-deps chromium

      - name: Run RPA Script
        env:
          SQUADBEYOND_ID: ${{ secrets.SQUADBEYOND_ID }}
          SQUADBEYOND_PASS: ${{ secrets.SQUADBEYOND_PASS }}
          GAS_WEBAPP_URL: ${{ secrets.GAS_WEBAPP_URL }}
          
          ROW_IDX: ${{ github.event.client_payload.row_idx }}
          
          # コピー元の情報
          GROUP_LIST_NAME_SOURCE: ${{ github.event.client_payload.group_list_name_source }}
          FOLDER_NAME_SOURCE: ${{ github.event.client_payload.folder_name_source }}
          SOURCE_ARTICLE: ${{ github.event.client_payload.source_article }}
          
          # コピー先の情報
          MCC_TEAM: ${{ github.event.client_payload.mcc_team }}
          DOMAIN: ${{ github.event.client_payload.domain }}
          GROUP_LIST_NAME_DEST: ${{ github.event.client_payload.group_list_name_dest }}
          FOLDER_NAME_DEST: ${{ github.event.client_payload.folder_name_dest }}
          
          # その他の情報
          DELIVERY_URL: ${{ github.event.client_payload.delivery_url }}
          ACCOUNT_NAME: ${{ github.event.client_payload.account_name }}
          
        run: node task.js

      - name: Upload Error Screenshot
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: error-screenshot.png
          retention-days: 3

      - name: Upload Success Screenshot
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: final-check
          path: final-check.png
          retention-days: 3
